// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": "Home",
  "about": "About",
  "conditions": "Conditions",
  "contact": "Contact",
  "getInTouch": "Get in Touch"
};
export default messages;